// var brick;
var gltfLoader;
var brickClone;
var scene;
var group1 = new Array();
var geometryMaterial1;
var brickContainer ;
var ground;
var landscape;
var wallGeometry;
var geometryMaterial;
var brickLoaded = false;
var brickLoaded2 = false;
var groupContainer;
var geometryMaterial2;
var groupContainerTop;
var brickGeometry;
// var torch;
var torchClone;
var torchLoaded = false;
var torch2;
var torchClone2;
var torchLoaded2 = false;
// var box;
var boxClone;
var boxLoaded = false;
// var spear;
var spearLoaded = false;
var spearClone;
var cupLoaded = false;
// var cup;
var cupClone;
var spearLoaded2 = false;
var boxLoaded2 = false;
var loading = 40;
var GameLoaded = false;
